		ORG 0000H
	OVEN_HOT BIT P2.3
	BUZZER	BIT P1.5
HERE:	JNB OVEN_HOT,HERE ;IF OVEN IS 1 ,WILL GO NEXT OR IF IT IS 0 WILL STAT HERE
		ACALL DELAY	; WAIT TIME
		CPL BUZZER 	;IT BIT WILL CHANGE 0
		ACALL DELAY	;WAIT TIME
		SJMP HERE	; WILL GO HERE,KEEP GOING
		END  